interface Canteen {
   id: number,
   name: string,
}

const CANTEENS: Canteen[] = [
   {id: 147, name: "Mensa HU Nord"},
   {id: 191, name: "Mensa HU Oase Adlershof"},
   {id: 270, name: "Backshop HU Spandauer Straße"},
   {id: 271, name: "Mensa FU Herrenhaus Düppel"},
   {id: 277, name: "Backshop FU Rechtswissenschaften"},
   {id: 319, name: "Mensa HTW Wilhelminenhof"},
   {id: 320, name: "Mensa HTW Treskowallee"},
   {id: 321, name: "Mensa TU Hardenbergstraße"},
   {id: 322, name: "Mensa FU II"},
   {id: 323, name: "Mensa FU I"},
   {id: 367, name: "Mensa HU Süd"},
   {id: 368, name: "Backshop FU OSI"},
   {id: 526, name: "Mensa HWR Badensche Straße"},
   {id: 527, name: "Mensa Berliner Hochschule für Technik Luxemburger Straße"},
   {id: 528, name: "Mensa FU Lankwitz Malteserstraße"},
   {id: 529, name: "Mensa EHB Teltower Damm"},
   {id: 530, name: "Mensa KHS Weißensee"},
   {id: 5302,name: "Backshop TU Hardenbergstraße"},
   {id: 531, name: "Mensa HfM Charlottenstraße"},
   {id: 532, name: "Backshop KHSB"},
   {id: 533, name: "Mensa HfS Ernst Busch"},
   {id: 534, name: "Mensa ASH Berlin Hellersdorf"},
   {id: 537, name: "Mensa Charité Zahnklinik"},
   {id: 538, name: "Mensa TU Marchstraße"},
   {id: 540, name: "Mensa Pastaria TU Architektur"},
   {id: 541, name: "Backshop TU Wetterleuchten"},
   {id: 542, name: "Mensa FU Pharmazie"},
   {id: 5477,name: "Backshop BHT Luxemburger Straße"},
   {id: 5501,name: "Backshop HfM Charlottenstraße"},
   {id: 631, name: "Mensa Pasteria TU Veggie 2.0 – Die vegane Mensa"},
   {id: 657, name: "Mensa TU „Skyline“"},
   {id: 660, name: "Mensa FU Koserstraße"},
   {id: 661, name: "Backshop HU „c.t.“"},
   {id: 723, name: "Backshop HfM Neuer Marstall"},
   {id: 727, name: "Backshop HWR Alt-Friedrichsfelde"},
];

export default CANTEENS;